
spring:
  profiles:
    active: dev
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      #username: @mongo.username@
      #password: @mongo.password@
      uri: @mongo.uri@
      #database: @mongo.database@
      #authentication-database: admin


logging:
  level:
    win.ots.sheol.api.repository : debug

